name: Node CI

on:
  push:
    branches:
      - 'main'
      - 'develop'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ['16']

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        run: |
          npm i -g pnpm@6
          pnpm -v

      - name: Install packages
        run: pnpm i

      - name: Build (cmd)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: pnpm -r --workspace-concurrency=1 run build

      - name: Build
        run: pnpm -r --workspace-concurrency=1 run build

      - uses: actions/github-script@v5
        with:
          script: |
            const { spawnSync } = require('child_process');
            try {
              const p = spawnSync('git', ['diff', 'lib']);
              if (p.status !== 0 || p.stdout.length !== 0) {
                core.setFailed(`diff lib detected`);
              }
            } catch (err) {
              core.setFailed(`diff lib failed: ${err}`);
            }

      - name: Test
        run: pnpm -r run test_c
